# Generated by Django 4.2.18 on 2025-01-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=256, verbose_name='Город')),
                ('adress', models.CharField(blank=True, max_length=256, verbose_name='Адресс')),
            ],
        ),
    ]
