# Generated by Django 4.2.19 on 2025-02-16 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Ресторан', 'verbose_name_plural': 'Рестораны'},
        ),
        migrations.AlterField(
            model_name='cities',
            name='adress',
            field=models.CharField(blank=True, max_length=256, verbose_name='Точный Адресс'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='adress',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cities', verbose_name='Город'),
        ),
    ]
