# Generated by Django 4.2.18 on 2025-01-27 06:54

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[account.models.validate_birth_date], verbose_name='Birthday Date'),
        ),
    ]
