# Generated by Django 4.2.19 on 2025-02-16 23:05

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cities_options_alter_restaurant_options_and_more'),
        ('account', '0006_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aboutMe',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='О Пользователе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[account.models.validate_birth_date], verbose_name='День Рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cities', verbose_name='Город Проживания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='food',
            field=models.CharField(blank=True, max_length=50, verbose_name='Любимая Еда'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('D', '...')], default='D', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Номер Телефона'),
        ),
    ]
