# Generated by Django 4.2.19 on 2025-02-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_aboutme_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Аватар Пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан'),
        ),
    ]
