# Generated by Django 4.2.19 on 2025-02-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cities_options_alter_restaurant_options_and_more'),
        ('account', '0008_user_profilepic_user_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cities', verbose_name='Город Проживания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('D', '...')], default='D', max_length=10, verbose_name='Пол'),
        ),
    ]
