# Generated by Django 4.2.19 on 2025-02-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='avatar/', verbose_name='Аватар Пользователя'),
        ),
    ]
