# Generated by Django 4.2.19 on 2025-02-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Номер Телефона'),
        ),
    ]
