# Generated by Django 4.2.18 on 2025-01-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_restaurant'),
        ('posts', '0003_alter_post_rating_alter_post_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.restaurant'),
        ),
    ]
