# Generated by Django 4.2.18 on 2025-01-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Звезда'), (2, '2 Звезды'), (3, '3 Звезды'), (4, '4 Звезды'), (5, '5 Звезд')], default='5', verbose_name='Рейтинг'),
        ),
    ]
