# Generated by Django 4.2.18 on 2025-01-26 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_post_rating_alter_post_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='5', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='review',
            field=models.TextField(max_length=1024, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
