# Generated by Django 4.2.18 on 2025-01-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
