# Generated by Django 4.2.19 on 2025-02-15 19:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_postinfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postinfo',
            unique_together={('user', 'post')},
        ),
    ]
