# Generated by Django 4.2.18 on 2025-01-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aboutMe',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='About Me'),
        ),
    ]
