# Generated by Django 4.2.18 on 2025-01-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'city', 'verbose_name_plural': 'Cities'},
        ),
    ]
